	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=startframe;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=startframe;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=startframe;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=startframe;
	
	
	
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=ledframe;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=0;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=red;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=0;
	
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=ledframe;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=blue;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=0;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=0;
	
		while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=ledframe;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=0;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=0;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=red;
	
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=stopframe;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=stopframe;
	while(!(USARTC0_STATUS& USART_DREIF_bm));
	USARTC0_DATA=stopframe;
